name: Mac N64 Builder

on:
  workflow_dispatch:

jobs:
  build-unix:
    strategy:
      fail-fast: false
      matrix:
        include: [
          { os: macos-latest, ext: "dylib" }
        ]
        
    runs-on: ${{matrix.os}}

    steps:      
      - name: Initialize repository
        uses: actions/checkout@v2
        with:
          ref: main
          persist-credentials: true
          fetch-depth: 0

      - name: Setup installation dependencies
        run: |
          if ${{runner.os == 'macos'}}; then
            brew update
            brew install cmake glew sdl2 sdl2_net freeglut nasm speexdsp libsamplerate boost

            SOURCE=/Library/Developer/CommandLineTools/SDKs
            TARGET=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
          
            for FILE in $(ls $SOURCE); do
              echo $FILE
              if [ ! -f "$TARGET/$FILE" ]; then
                ln -s "$SOURCE/$FILE" "$TARGET/$FILE"
              fi
            done
          fi

      - name: Initializing submodules and creating temporary workspace
        run: |
          git submodule update --init --recursive --checkout --quiet

          echo "Confirm we have a bin directory..."
          if [ ! -d "bin" ]; then
            mkdir "bin"
          fi
          if [ ! -d "bin/N64" ]; then
            mkdir "bin/N64"
          fi

          echo "Making temporary repository to create packages in..."
          mkdir "N64/tmp"
          mkdir "N64/tmp/consoles"
          mkdir "N64/tmp/consoles/n64"
          mkdir "N64/tmp/consoles/n64/emulator"

          # Define a reuseable function
          echo "
            LIB=\"\$1\"
            BIN=\"\$2.${{matrix.ext}}\"
            cd \"N64/\$LIB/projects/unix\"
            make all
            cp \"\$BIN\" \"../../../tmp/consoles/n64/emulator/\$BIN\"
          " >> N64/tmp/build_plugin.sh

      - name: Building mupen64plus-core
        run: |
          sh N64/tmp/build_plugin.sh "mupen64plus-core" "mupen64plus"
          
      - name: Building mupen64plus-audio-sdl
        run: |
          LIB="mupen64plus-audio-sdl"
          sh N64/tmp/build_plugin.sh "$LIB" "$LIB"
          
      - name: Building mupen64plus-input-sdl
        run: |
          LIB="mupen64plus-input-sdl"
          sh N64/tmp/build_plugin.sh "$LIB" "$LIB"
          
      - name: Building mupen64plus-rsp-cxd4-sse2
        run: |
          LIB="mupen64plus-rsp-cxd4-sse2"
          sh N64/tmp/build_plugin.sh "$LIB" "$LIB"
          
      - name: Building mupen64plus-rsp-hle
        run: |
          LIB="mupen64plus-rsp-hle"
          sh N64/tmp/build_plugin.sh "$LIB" "$LIB"
          
      - name: Building mupen64plus-rsp-z64
        run: |
          LIB="mupen64plus-rsp-z64"
          sh N64/tmp/build_plugin.sh "$LIB" "$LIB"
          
      - name: Building mupen64plus-video-arachnoid
        run: |
          if ${{runner.os == 'macos'}}; then exit 0; fi
          LIB="mupen64plus-video-arachnoid"
          sh N64/tmp/build_plugin.sh "$LIB" "$LIB"
          
      - name: Building mupen64plus-video-glide64mk2
        run: |
          if ${{runner.os == 'macos'}}; then exit 0; fi
          LIB="mupen64plus-video-glide64mk2"
          sh N64/tmp/build_plugin.sh "$LIB" "$LIB"
          
      - name: Building mupen64plus-video-rice
        run: |
          LIB="mupen64plus-video-rice"
          sh N64/tmp/build_plugin.sh "$LIB" "$LIB"
          
      - name: Building mupen64plus-video-z64
        run: |
          LIB="mupen64plus-video-z64"
          sh N64/tmp/build_plugin.sh "$LIB" "$LIB"
          
      - name: Building mupen64plus-video-angrylion-plus
        run: |
          LIB="mupen64plus-video-angrylion-plus"
          BIN="$LIB.${{matrix.ext}}"
          mkdir "N64/$LIB/build"
          cd "N64/$LIB/build"
          cmake -G "Unix Makefiles" ".."
          make
          cp "$BIN" "../../tmp/consoles/n64/emulator/$BIN"

      - name: Auditing files
        run: |
          ls "N64/tmp/consoles/n64/emulator"

      - name: Cloning data folder contents
        run: |
          cp -a "N64/mupen64plus-core/data/." "N64/tmp/consoles/n64/emulator/"
          cp -a "N64/mupen64plus-input-sdl/data/." "N64/tmp/consoles/n64/emulator/"
          cp -a "N64/mupen64plus-video-rice/data/." "N64/tmp/consoles/n64/emulator/"
          cp -a "N64/mupen64plus-video-glide64mk2/data/." "N64/tmp/consoles/n64/emulator/"
          cp -a "N64/mupen64plus-video-glide64mk2/data/." "N64/tmp/consoles/n64/emulator/"
          
      
      - name: Auditing new file collection
        run: |
          ls "N64/tmp/consoles/n64/emulator"
    
      - name: Generate package
        run: |
          cd "N64/tmp"

          if ${{runner.os == 'linux'}}; then
            tar -czf "../../bin/N64/linux.tar.gz" "consoles"
          elif ${{runner.os == 'macos'}}; then
            zip -r "../../bin/N64/macos.zip" "consoles"
          fi

      - name: Cleaning up files
        run: |
          rm -r "N64/tmp"

      - name: Pull and Stage changes
        run: |
          if ${{runner.os == 'linux'}}; then
            FI="bin/N64/linux.tar.gz"
          elif ${{runner.os == 'macos'}}; then
            FI="bin/N64/macos.zip"
          fi
          
          git stash
          git pull --rebase
          git stash pop
          git add "$FI"
          git checkout --ours -- "$FI"

      - name: Commit & push package
        uses: actions-js/push@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          message: "Updated N64 packages."
